from django.db import models
import datetime

# Create your models here.
class Room(models.Model):
    # id is auto-generated by django
    name = models.CharField(max_length=1000)


class Message(models.Model):
    # id is auto-generated by django
    message_content = models.CharField(max_length=1000000)
    date_sent = models.DateTimeField(default=datetime.datetime.now, blank=True)
    sent_by_user = models.CharField(max_length=1000000)
    from_which_room = models.CharField(max_length=1000000)
